homieiot/homie-esp8266

src/Homie.h
=> Fix small bug with setNodeProperty

config.xml
I created a basic config.xml for Phonegap so it builds as an app.
You can test it here. (Android and Windows Phone only since I do not have a iOS developer license.)
[PhoneGap Build](https://build.phonegap.com/apps/1896165/share)
=> Added config.xml for phonegap build

keywords.txt, src/Homie.cpp, src/Homie.h, src/Homie/Boot/Boot.cpp, src/Homie/Boot/BootConfig.cpp, src/Homie/Boot/BootNormal.cpp, src/Homie/Constants.hpp, src/Homie/Datatypes/SharedInterface.hpp
allow changing the "Homie" string of hostname / SSID
`Homie.setBrand("MyBrand");`
=> custom branding

src/Homie.cpp, src/Homie.hpp, src/Homie/Boot/BootNormal.cpp, src/Homie/Datatypes/Interface.hpp
As proposed in #142 , I added a broadcast channel.
Sample implementation is at https://github.com/euphi/ESP_Heizungscontroller . (It does not make real use of it, it just logs the received message to Serial and back to MQTT).
=> #142: Add broadcast channel

src/Homie/Boot/BootNormal.cpp
Sorry, I forgot to include one diff in my last PR.
=> Bugfix last PR (always subscribe to $ota even if ota disabled)

src/Homie/Boot/BootNormal.cpp
=> Renamed $implementation/ota/payload topic to $implementation/ota/firmware

src/Homie/Boot/BootNormal.cpp, src/Homie/Boot/BootNormal.hpp
- correct one leftover comment that @marvinroger noticed
- now checks firmware size when base64-padding is present
=> be more explicit about base64-padding

examples/IteadSonoffButton/IteadSonoffButton.ino
hi, this example is running on my devices and works great. this may also be useful for others.
=> add iteadsonoff example that includes pushbutton handling

src/Homie/Boot/BootNormal.cpp
Fixed an issue decoding base64. The first base64 characters of consecutive payload chunks were not handled correctly. The first two base64 characters matter, not just the first one.
This should fix #208.
=> Bugfix: base64 decoding

src/Homie.cpp, src/Homie.hpp, src/Homie/Boot/BootConfig.cpp, src/Homie/Boot/BootNormal.cpp, src/Homie/Boot/BootNormal.hpp, src/Homie/Boot/BootStandalone.cpp, src/Homie/Config.cpp, src/Homie/Config.hpp, src/Homie/Constants.hpp, src/Homie/Datatypes/Interface.cpp, src/Homie/Datatypes/Interface.hpp, src/Homie/TimedRetry.cpp, src/Homie/TimedRetry.hpp, src/Homie/Timer.cpp, src/Homie/Timer.hpp
=> Simplification on boot modes logic. Now any mode can be triggered programmatically or scheduled for the next boot. + MQTT retry enhancements

src/Homie.cpp, src/Homie/Boot/BootConfig.cpp, src/Homie/Boot/BootConfig.hpp, src/Homie/Boot/BootNormal.cpp, src/Homie/Config.cpp, src/Homie/Datatypes/Interface.cpp, src/Homie/Limits.hpp, src/Homie/Utils/DeviceId.cpp, src/Homie/Utils/DeviceId.hpp
Added length checks on some strings.
Fixed Compiler warning - "list-initializer for non-class type must not be parenthesized"
=> Length checks on input fields. 

src/Homie/Uptime.cpp, src/Homie/Uptime.hpp
Corrected type declaration for correct overflow handling of millis
function in uptime calculation
=> #299 Handling millis() overflow in uptime

src/Homie/Boot/BootConfig.cpp
See issue #361 and https://github.com/bblanchon/ArduinoJson/issues/541.
=> Fix compatibility with ArduinoJson 5.11.0

src/Homie/Boot/BootConfig.cpp
Bringing in ArduinoJSON 5.11.0 fix from https://github.com/marvinroger/homie-esp8266/pull/362
Closes https://github.com/marvinroger/homie-esp8266/issues/361 again.
=> ArduinoJSON 5.11.0 fix from master

src/Homie/Boot/BootNormal.cpp
Skip node publication if HomieNode::nodes.size() == 0
=> Fix crash when starting up without any defined node

src/Homie/Boot/BootNormal.cpp
Fixes the module crashing as soon as firmware is published into the topic
=> Change topic check for OTA upload

docs/advanced-usage/range-properties.md
Add hint to help people figure out how to interact with
range properties. Especially document the `_` separator.
=> 🤔 Add details on how to interact with range property

scripts/ota_updater/ota_updater.py
Fix https://github.com/marvinroger/homie-esp8266/issues/397
=> Interpret firmware file as an bytearray

docs/quickstart/getting-started.md, library.json, src/Homie/Boot/BootConfig.cpp, src/Homie/Boot/BootConfig.hpp, src/Homie/Boot/BootNormal.cpp, src/Homie/Boot/BootNormal.hpp, src/Homie/Boot/BootStandalone.cpp, src/Homie/Boot/BootStandalone.hpp, src/Homie/Strings.hpp, src/Homie/Timer.cpp, src/Homie/Utils/ResetButton.cpp, src/Homie/Utils/ResetButton.hpp, src/HomieSetting.cpp, src/HomieSetting.hpp
Moved Config Mode to use AsyncWebServer + lots of refactoring.
Also plan on continuing to refactor homie.
=> AsyncWebServer + Refactoring

.circleci/config.yml
Sorry, now I understand why you re-install library from existing sources... Just to install dependencies. This is a good idea! Sorry again!
=> Install library via @PlatformIO with all dependencies

README.md
Found a few links were 404's under the Features section
=> Fix links under Features

src/HomieNode.cpp
introduced with commit 9968042d7107cd3b17617aa51e10963277112450.
=> Fixed reorder warning

.circleci/config.yml, examples/Ping/src/main.cpp
* added ESP32 board to the example builds
* added missing examples end reordered them,
=> CircleCI: add ESP32 builds

src/Homie/Boot/BootNormal.cpp
Hi guys!
Thanks to the great instructions provided by @jeanvdr and @bertmelis, OTA updates are now working for ESP32 boards. I don't have any ESP8266 with me right now, so please test it on those boards before merging!
Closes #575
Signed-off-by: Aitor Iturrioz <riturrioz@gmail.com>
=> Fix OTA problems for ESP32

src/Homie.cpp
=> add workaround for issue #351

src/HomieNode.cpp
(cherry picked from commit 124992d174ce9724564bed85ada8125844585fcd)
=> Fixed reorder warning (#578)

docs/index.md
=> Grammar fix

src/Homie/Boot/BootNormal.cpp
* Fix wrong MQTT topic buffer size calulation which might lead to a buffer overflow
=> Fix potential MQTT topic buffer overflow

src/Homie/Boot/BootConfig.cpp, src/Homie/Config.cpp, src/Homie/Utils/Validation.cpp
* Simplify JSON lookups
* Remove unnecessary lookups
* Add null checks for JSON strings before calling strlen()
=> Optimize JSON code

src/Homie/Boot/BootNormal.cpp
+ During OTA do not publish any messages that are not OTA related
+ Publish 1 every 100 206 status messages
=> (#648) Tweaks to avoid OTA halting when using TLS.

docs/configuration/json-configuration-file.md
=> Added info about max length

examples/testAllInputHandlers/testAllInputHandlers.ino
It took me some time figuring out how to use the different input handlers. 
I created an example sketch for all types of input handlers (except the virtual one)
Tested on PlatformIO
=> Examples sketches for all type of Input Handlers

docs/advanced-usage/custom-settings.md, docs/advanced-usage/miscellaneous.md
2 parts added:
- Proposal for optimal sketch structure.
- Managing MQTT messages while offline.
Comments are welcome :)
=> Advanced usage/Miscellaneous - tips

src/Homie.cpp, src/Homie.hpp
I added the deep sleep functionality for ESP32 according to the documentation: https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/system/sleep_modes.html
=> Added deep sleep functionality for ESP32

component.mk
Add a simple component.mk to allow compiling homie as esp-idf (v3) component.
=> Add component.mk

src/Homie/Boot/BootNormal.cpp
although C++ operator precedence would be correct in this case
=> fix suggested parentheses warning

docs/advanced-usage/input-handlers.md
=> #608 correction of doc for globalInputHandler
