README.md
src/Homie/Boot/BootConfig.cpp
src/Homie/Boot/BootNormal.cpp
src/Homie/Boot/BootOta.cpp
src/Homie/Config.cpp
src/Homie/Config.hpp
src/Homie/Constants.hpp

This should close #3, this also include #6 but with to call to the log mth : 
* when config is saved in config mode
* at setup time in normal mode

Add MQTT port and OTA path & port to config

---

src/Homie/Constants.hpp

One line PR.
D3 (== GPIO0) is not defined when you are not using NodeMCU board in the arduino IDE, so you get a compilation error.
I guess float instead of uint was a copy past mistake...
Bytheway, I'm thinking to make this reset a bit more configurable... at least the PIN, but maybe also the "delay". An other way is to expose a function to manually trigger the reset from main code...

Change PIN_RESET to uint8_t and value to 0 (not D3)

---

src/Homie/Boot/BootNormal.cpp

I believe the logic is wrong: verification should be performed if the fingerprint string is not empty.
Addresses #42

Verify if fingerprint is NOT empty

---

src/Homie/Datatypes/Callbacks.hpp

I'm working on a sensor network projekt, using your excellent Homie framework. I have different sensors (light, temperature), and some actors (led, relay). I modularized my code, so I have a class for every kind of device. And I'm unable to subscribe my HomieNodes to topics when I'm inside of a method.
The problem is, that `HomieNode.subscribe()` only takes a function pointer as a second parameter, which I'm unable to provide. I'd rather give a function object.
With this change I'm able to subscribe my method `ledOnHandler()` in one of these two ways:
```
ledNode.subscribe("on", [this](String value) { return ledOnHandler(value); });
ledNode.subscribe("on", std::bind(&DeviceLed::ledOnHandler, this, std::placeholders::_1));
```
I successfully tested that the old way of doing this still …

replaced function pointer with function object

---

src/Homie/Boot/BootNormal.cpp

MDNS.begin() must be called prior to MDNS.queryService(), otherwise the
app will crash.
Also, it crashed when using the result IP because the pointer returned
by String::c_str() is freed when the String is destroyed.

Enabling mDNS causes an app crash (issue #79)

---

src/Homie/Boot/Boot.cpp

This way it shows properly in the router device list and the router may resolve
DNS queries from computers not supporting multicast DNS (Microsoft Windows).

Use deviceId as hostname

---

src/Homie.cpp
src/Homie.hpp
src/Homie/Boot/BootNormal.cpp
src/Homie/Datatypes/Interface.hpp
src/HomieNode.cpp
src/HomieNode.hpp

This is an alternate implementation of @euphi idea.
I've removed all the non essential editions (serial flush on some errors, disable mDNS) and I've added the onReadyToOperate() virtual method I proposed in my previous merge request.

Add several virtual methods to HomieNode

---

src/Homie.cpp
src/Homie.hpp
src/Homie/Config.cpp
src/Homie/Config.hpp
src/HomieNode.cpp
src/HomieNode.hpp

This method allows to publish raw MQTT topics.
It also exposes accessor methods to get the MQTT base topic and the
identifiers of the Homie device and nodes.
This alternative implementation goes away with getNodeTopic(), since it can be implemented using the accessors, which are inline functions which doesn't generate code if unused.

Add method Homie::publishRaw

---

README.md
docs/2.-Getting-started.md
docs/7.-API-reference.md
examples/DoorSensor/DoorSensor.ino
examples/IteadSonoff/IteadSonoff.ino
examples/LedStrip/LedStrip.ino
examples/LightOnOff/LightOnOff.ino
examples/TemperatureSensor/TemperatureSensor.ino
keywords.txt
src/Homie.cpp
src/Homie.hpp
src/Homie/Boot/BootConfig.cpp
src/Homie/Boot/BootNormal.cpp
src/Homie/Datatypes/Interface.hpp
src/Homie/Limits.hpp
src/HomieNode.cpp
src/HomieNode.hpp

It removes the array of nodes from Datatypes/Interface.hpp and converts
it to a linked list. First & last pointers are stored as static members
of HomieNode.
Also, it adds 3 static methods to HomieNode: for_each() that executes a
lambda function on every registered node, find() which looks up a node,
and getNodeCount() which returns the number of registered nodes.

Proposal for autoregistration of HomieNodes

---

docs/6.-Configuration-API.md
src/Homie/Boot/BootConfig.cpp
src/Homie/Boot/BootConfig.hpp

@marvinroger, as discussed in #26, I had implemented some apis for enabling more customized captive portals with minor impacts in base Homie firmware. With those apis in place, the developer can use the existing "ui_bundle.gz" capabilities to perform custom interactions with the user and/or cloud services.

Transparent proxy for captive portal custom configurations

---

src/Homie/Boot/BootNormal.cpp
src/Homie/Boot/BootNormal.hpp

See #172 
Here is a little test script for triggering OTA updates with a checksum:
#!/bin/bash
DEVICE=homie/awesome-relay
BROKER=localhost
FW_VER=1.0.0
FW_BIN=/path/to/firmware.bin
FW_MD5=$(md5sum -b $FW_BIN | cut -d" " -f1)
mosquitto_pub -h $BROKER -t "$DEVICE/\$ota" -m "$FW_VER"
sleep 1
mosquitto_pub -h $BROKER -t "$DEVICE/\$implementation/ota/checksum" -m $FW_MD5
sleep 1
mosquitto_pub -h $BROKER -t "$DEVICE/\$implementation/ota/firmware" -f $FW_BIN

Added OTA checksum verification

---

src/Homie/Boot/BootNormal.cpp
src/Homie/Boot/BootNormal.hpp

See #172. 
Again, a little test script (this time, without sleep's ;-)):
#!/bin/bash
DEVICE=homie/awesome-relay
BROKER=localhost
FW_VER=1.0.0
FW_BIN=/path/to/firmware.bin
FW_MD5=$(md5sum -b $FW_BIN | cut -d" " -f1)
FW_B64=${FW_BIN/.bin/.b64}
base64 -w0 $FW_BIN > $FW_B64
mosquitto_pub -h $BROKER -t "$DEVICE/\$ota" -m "$FW_VER"
mosquitto_pub -h $BROKER -t "$DEVICE/\$implementation/ota/checksum" -m $FW_MD5
mosquitto_pub -h $BROKER -t "$DEVICE/\$implementation/ota/firmware" -f $FW_B64
Please note the `-w0` option with `base64`. This option turns off line wrapping which would otherwise stop Homie from correctly calculating the new firmware size based on the length of the `$implementation/ota/firmware` payload. I think it should be mentioned in the docs that non-base64 characters are not …

Added support for base64-encoded firmware

---

src/Homie/Boot/BootNormal.cpp

If an OTA server publishes firmware to `$implementation/ota/firmware`
- to a Homie device with OTA disabled, or 
- without having sent a new firmware version to `$ota` first
then Homie replies `403` (forbidden) or `400 NOT_REQUESTED` status for every chunk of payload it receives (which is about 350 times for a simple firmware).
This PR makes Homie reply only once per MQTT message.

Reject ota/firmware only once (vs. with every payload chunk)

---

src/Homie/Boot/BootNormal.cpp
src/Homie/Boot/BootNormal.hpp

I noticed an issue with base64-encoded OTA updates: for some firmware base-encoded OTA update worked and for some it didn't.
It turned out that, if the real firmware size modulo 3 equaled 1, firmware was incorrectly rejected with `400 BAD_FIRMWARE`. The reason was that the code I added only expected the real firmware size to be off by **one** from the "guestimated" size (3/4 ratio of the total length of the `=` padded base64 payload). However, the real firmware size may as well be off by **two** from the 3/4 ratio.
Examples with some realistic firmware sizes:
Real firmware size | Real size modulo 3 | Base64 length | Base64 Padding | Estimated firmware size | Size off-by
-------------------| ------------------ | ------------- | -------------- | ----------------------- | -----------
346992 …

Bugfix base64-encoded firmware when (size mod 3) equals 1

---

src/Homie/Boot/BootNormal.cpp

I noticed unterminated-string garbage in the log output... Probably not related to the open OTA issues.

bugfix: wrong buffer used when logging received ota checksum

---

src/Homie/Boot/BootNormal.cpp
src/Homie/Boot/BootNormal.hpp

Implements #220 
Note that, if OTA fails, we don't need to restart anymore just for resetting the expected MD5 because now there WILL be another SetMD5() when the server retries the update.
Updated bash script:
#!/bin/bash
DEVICE=homie/<device>
BROKER="-h <broker>"
FW_BIN=/path/to/firmware.bin
FW_MD5=$(md5sum -b $FW_BIN | cut -d" " -f1)
FW_B64=${FW_BIN/.bin/.b64}
base64 -w0 $FW_BIN > $FW_B64
mosquitto_pub $BROKER -t "$DEVICE/\$implementation/ota/checksum" -m $FW_MD5
mosquitto_pub $BROKER -t "$DEVICE/\$implementation/ota/firmware" -f $FW_B64
I added a second commit to be slightly more consistent with icons and OTA message grammar.

Patch replace ota version with checksum

---

src/Homie/Boot/BootNormal.cpp

When several devices are used and several are waiting their configuration, it is useful to check the mac address in Homie-ota server. Thanks to this change, the mac appear in inventory of the device in homie-ota server.

Add mac info message on boot normal

---

src/Homie/Boot/BootNormal.cpp

Just got an endless loop when I used a retained message for patching Homie configuration. Clearing the message (publish an "" to the topic) before rebooting will avoid this.

Clearing config/set topic after applying patch to avoid endless loops when using retained messages

---

src/Homie/Boot/BootNormal.cpp

@marvinroger Meaculpa, previous commit was completly wrong. This one should fix it.
Please see issue #250 for more details
More generally, with the direct access to MQTT client(getMqttClient()) and so topic arriving could be anything, don't you think "brand/device-id" should be checked each time before processing any topic?
Checking only from device assumes that brand is the same. But those can be different at the content and the length level implying shift in the device-id comparison. And Maybe creating false positive if brand name contain device-id name...
Update: rebased fix for PR

[BootNormal] Fix, Bad topic used for device name detection

---

src/Homie/Boot/BootConfig.cpp

CORS for `/wifi/connect`
Using the same code for handling CORS requests for `/config`.
Use case: if the configurator is a separate website/webapp.

CORS for /wifi/connect

---

src/Homie/Boot/BootNormal.cpp

Previously the check was 
` if (!Interface::get().connected) { return; }`
Fixed brackets to ensure loopFunction is only called when homie is connected

Fixing loopFunction being called too early before MQTT connection is established

---

src/Homie/Boot/BootNormal.cpp

This removes the need to hunt the device IP when debugging connectivity issues.

Log wifi client IP address upon connection.

---

src/HomieNode.cpp

E.g. https://travis-ci.org/marvinroger/homie-esp8266/jobs/199213998
Ran the following command successfully:
cpplint --repository=. --recursive \
--filter=-whitespace/line_length,-legal/copyright,-runtime/printf,-build/include,-build/namespace,-runtime/int \
./src

Fix cpplint failure, causing travis CI to be red

---

src/Homie/Boot/BootNormal.cpp

Fix for #301: Remove hardcoded KeepAlive for MQTT connection.
Default value of 15sec is already present in AsyncMQTT library.
Custom keepalive value got overwritten by the hardcoded one, but Homie would ping based on the custom setting.

Fix #301 remove hardcoded keepalive

---

src/Homie/Uptime.cpp
src/Homie/Uptime.hpp

improve uptime accuracy by storing milliseconds and only rounding when publishing value
drawback: less time before rollover uptime, but still long enough

Improve uptime accuracy

---

src/Homie/Boot/BootNormal.cpp

Fix for truncated published IP as in issue #309

Fix truncated IP #309

---

src/Homie/Boot/BootNormal.cpp
src/Homie/Boot/BootNormal.hpp
src/Homie/Config.cpp
src/Homie/Datatypes/ConfigStruct.hpp
src/Homie/Limits.hpp
src/Homie/Utils/Helpers.cpp
src/Homie/Utils/Helpers.hpp
src/Homie/Utils/Validation.cpp
src/Homie/Utils/Validation.hpp

Support for static IP and BSSID/MAC, Channel of AP
- added parameters to config.json which allow to define static ip, mask,
gateway, dns
- added parameters to config.json which allow to define BSSID and
channel of AP
To run device with defined static IP you have to define ip, mask and
gateway together.
To point device to connect to specific BSSID and channel you haveto
define bssid and channel together.
```
{
"name": "The kitchen light",
"device_id": "kitchen-light",
"wifi": {
"ssid": "Network_1",
"password": "I'm a Wi-Fi password!",
"bssid": "DE:AD:BE:EF:BA:BE",
"channel": 1,
"ip": "192.168.1.5",
"mask": "255.255.255.0",
"gw": "192.168.1.1"
},
"mqtt": {
"host": "192.168.1.10",
"port": 1883,
"base_topic": "devices/",
"auth": true,
"username": "user",
"password": "pass" i
},
"ota": { …
```

Support for static IP and BSSID/MAC, Channel of AP

---

src/HomieSetting.cpp

Set initialization priority of IHomieSetting::settings to value of highest allowed priority (101).
This allows other static variables to be of type HomieSetting< T>.
See https://github.com/euphi/HomieNodeCollection/blob/master/src/RGBWNode.cpp for example.
Note: It makes sense to have a static HomieSetting member, if you have a class that may be instantiated multiple times. (e.g. two LED Strips connected to the same ESP8266, as shown in https://github.com/euphi/ESP-LEDCtrl).

 IHomieSetting::settings first, HomieNode-settings second!

---

src/Homie.cpp

`HomieClass& HomieClass::setConfigurationApPassword(const char* password)` did not returned a reference to the Homie instance. This PR fixes this.

Fix: not returning a value in a method that returns non-void

---

src/Homie/Boot/BootConfig.cpp

The example JSON configuration provided at http://marvinroger.github.io/homie-esp8266/stable/5.-JSON-configuration-file/ fails to load when using the master/"stable" branch of this library when built against the latest version of ArduinoJSON due to issue #178. Therefore, I would recommend incorporating this fix into the stable branch since such bug severely limits functionality, and the fix for such does not break compatibility with existing implementations.

Backport fix for issue #178 into master/stable branch

---

.circleci/config.yml

It seems the last moment. Development branch depend on staging version of ESP8266 Core for Arduino

CI: Install staging version of Arduino Core for ESP8266 & @PlatformIO

---

docs/configuration/http-json-api.md

Docs show `/wifi/connect` as `GET` when it should actually be `PUT`

Correct API docs for /wifi/connect from GET to PUT

---

scripts/ota_updater/ota_updater.py

My MQTT broker refuses connections that aren't made over TLS, so I can't use the ota_updater script as-written. This PR adds a `--broker-tls-cacert` that enables TLS for the connection and sets the the CA cert bundle used to validate the connection
Additionally, this fixes a bug where the updater wouldn't work if the target device was asleep

Add option for ota_updater script to connect to TLS-protected brokers

---

README.md

A small documentation update so users set the `PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY` build flag for reliable OTA updates.

Require use of PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY

---

docs/advanced-usage/events.md
src/Homie/Boot/BootNormal.cpp
src/HomieEvent.hpp

I felt the need for an event that gets fired whenever Homie sends its statistics. 
E.G. currently I use this to send the free heap via MQTT.

Add an event that is fired whenever statistics are sent 

---

docs/advanced-usage/events.md

I think it is good to know, that the loop and setup functions of Homie are only called if MQTT is connected.

additional information about Homie.setup() and Homie.loop()

---

docs/others/cpp-api-reference.md
examples/LightOnOff/LightOnOff.ino

Not being able to simple insert a variable as parameter to the function `Homie_setFirmware` comes as a surprise. After checking the macro behind it, I believe this is the cleanest option for outsourcing of the firmware version - which you might want to do in bigger programs.
I wasn't sure where to put this info, decided to go with one of the basic examples and the api reference documentation. Better ideas?

Hint the use of a macro for fw version number

---

docs/advanced-usage/compiler-flags.md
src/Homie.cpp
src/Homie.hpp
src/Homie/Boot/BootConfig.cpp
src/Homie/Boot/BootConfig.hpp
src/Homie/Boot/BootNormal.cpp
src/Homie/Boot/BootStandalone.cpp
src/Homie/Constants.hpp
src/Homie/Utils/ResetHandler.cpp
src/Homie/Utils/ResetHandler.hpp
src/HomieBootMode.hpp

The added compiler flag that allows to remove the config mode from the code completely during compile run. This reduces the size of my empty test firmware by 50760 bytes.

added compiler flag for disabling the config mode

---

docs/advanced-usage/compiler-flags.md
src/Homie/Boot/BootNormal.cpp
src/Homie/Boot/BootNormal.hpp

Disabling mDNS in homie-esp8266 saves 6456 bytes of flash. I am trying to reduce the overall firmware size by disabling functionality, that I don't need.
I use ESP-01 and the 1MB flash size is too small to get OTA working. Therefore making homie-esp8266 is maybe an option to reduce firmware size and make OTA work on small devices.

Added compiler flag for disabling mDNS

---

docs/advanced-usage/events.md
examples/HookToEvents/HookToEvents.ino
src/Homie/Boot/BootNormal.cpp
src/HomieEvent.hpp

Follow-up to #566 Add an event that is fired whenever statistics are sent. 
- Fixed a typo in the code. Docs were ok.
- Update the example application.

Add output for SENDING_STATISTICS to the example application

---

.github/ISSUE_TEMPLATE.md
.gitignore
docs/README.md
docs/configuration/http-json-api.md
library.json
src/Homie/Boot/BootConfig.cpp

Correction of some URLs after the movement to organisation `homieiot`:
`http://marvinroger.github.io/homie-esp8266/` -> `https://homieiot.github.io/homie-esp8266/`

correction of some GitHub URLs

---

docs/advanced-usage/deep-sleep.md

In my testcases the provided example for deep-sleep mostly caused the properties of some HomieNodes sent in HomieNode::loop() method not to be received by the MQTT broker. Maybe this is due to new async SSL connection handling of my other pull request #577. The introduced postpone of going into deep sleep solved properly the properties of HomieNodes to be received by the MQTT broker.
Maybe there is a better solution by asking the MQTTclient for its state about sending messages, but I did not find one. If you point me to the right place, I will try to fix this correctly.

Extended documentation for deep-sleep

---

src/Homie/Boot/BootNormal.cpp

MQTT was not reconnecting after a loss, since BootNormal::_onMqttDisconnected had to be called [twice](https://github.com/homieiot/homie-esp8266/blob/develop/src/Homie/Boot/BootNormal.cpp#L500) in order to periodically try to reconnect.
In my tests it got called only once, leading to only one singe reconnection attempt.

Fixed device not reconnecting after MQTT connection loss

---

.circleci/config.yml
docs/advanced-usage/compiler-flags.md
docs/configuration/json-configuration-file.md
docs/others/limitations-and-known-issues.md
src/Homie/Boot/BootConfig.cpp
src/Homie/Boot/BootNormal.cpp
src/Homie/Config.cpp
src/Homie/Datatypes/ConfigStruct.hpp
src/Homie/Limits.hpp
src/Homie/Utils/DeviceId.cpp
src/Homie/Utils/DeviceId.hpp
src/Homie/Utils/Helpers.cpp
src/Homie/Utils/Helpers.hpp
src/Homie/Utils/Validation.cpp

This is stolen from timpur's v2.1 branch.
I like to encrypt my MQTT connections because passwords are transmitted over MQTT in clear text. Passwords transmitted in clear text should be always avoided.

SSL support for MQTT connection

---

src/Homie/Config.cpp

When the configSize is MAX_JSON_CONFIG_FILE_SIZE the '\0' is written
after the buffers end. Don't load config files with a
size >= MAX_JSON_CONFIG_FILE_SIZE.
Signed-off-by: Philipp Rosenberger <code@iluminat23.org>

Config: fix buffer overflow when loading json config

---

library.json
src/Homie/Boot/BootConfig.cpp
src/Homie/Config.cpp
src/Homie/Config.hpp
src/Homie/Utils/Validation.cpp
src/Homie/Utils/Validation.hpp

* Migrate the code from ArduinoJson v5 to v6
* Resolve memory allocation issues resulting from the migration
* Reduce unnecessary copying of some JSON related strings
* Change to StaticJsonBuffer if possible

Migrate to ArduinoJson version 6

---

src/Homie/Boot/BootNormal.cpp

When a device loses WiFi, it keeps MQTT connected during keepalive. Homie doesn't check for WiFi during loop -only MQTT is checked- so it keeps sending stats (and spamming serial console)
Bugfix will also prevent filling tcp buffer on long keepalives.

stop stats on disconnect

---

src/Homie/Boot/BootConfig.hpp

This removes then the complete dependency to ESPAsyncWebServer

Includes are not needed if config mode is disabled

---

docs/advanced-usage/events.md

The capitalization of the `setSetupFunction` usages was inconsistent, use camelCase.

Capitalization fix

---

src/Homie/Boot/BootNormal.cpp
src/Homie/Boot/BootNormal.hpp

It is not possible to subscribe to MQTT messages in general using Homie framework, as BootNormal::_onMqttMessage() truncates the topic.
[Issue #524](https://github.com/marvinroger/homie-esp8266/issues/524) 
With this change, topics can afterwards be intercepted by any other subscribed function, without loosing functionality

Subscribing to messages using Homie.getMqttClient() is not reliable: topic is truncated

---

src/Homie/Boot/BootNormal.cpp

Removed the lines copying the sketch MD5 at the BootNormal constructor
since that crashed the firmware. At that point the ESP object is not ready
to invoke getSketchMD5(). Also the code was duplicated since it's was
already invoked at the BootNormal::setup function with no issues.

getSketchMD5() at BootNormal constructor crashes on ESP32 (#641)

---

examples/LightOnOff/LightOnOff.ino

Closes #639 
Signed-off-by: Aitor Iturrioz <riturrioz@gmail.com>

Fix semicolon after define statement in LightOnOff example

---

src/Homie/Boot/BootNormal.cpp

Only copy the topic on the first message chunk. Otherwise the old copy will be
destroyed on subsequent calls to `_onMqttMessage()` for the same message, while
the copy is still being referenced by `_mqttTopicLevels`. This leads to undefined
behaviour.
Should solve #644 
Thanks @nemidiy for investigating this issue!

Fix topic copying for chunked messages

---

src/Homie/Boot/Boot.cpp

This is a workaround for issue #588. Disabling WiFi persistence will stop the crashes from occuring, as long as no other firmware with WiFi persistence has been ran on the ESP32 prior. In this case the internal flash needs to be wiped beforehand.

Add workaround for AP crash issues on ESP32

---

src/Homie/Boot/BootConfig.cpp
src/Homie/Boot/BootNormal.cpp
src/Homie/Config.cpp
src/Homie/Utils/Validation.cpp

- In the migration to ArduinoJson v6 I've introduced a bug disallowing the usage of `null` as `wifi.password`. Commit 25f6b8c fixes this.
- The parameter `ota.enabled` was treated as optional in the config load code, but not in the validation code. Commit 64ca0ba will make `ota.enabled` optional and default to disabled OTA.
- In Config::getSafeConfigFile(), a `char[]` buffer gets allocated within a `unique_ptr`, only to be copied and and then discarded at the end of the method. Commit 60ca263  removes this unnecessary step.

Various code optimizations

---

scripts/ota_updater/ota_updater.py

One line to fix both problems mentioned in #589:
Checking the "$state" topic for not "false" was wrong, because since v3
the online state must be "ready" to continue.
Thus, also in "init" state the ota-updater re-subscribed to the $fw
topic and thus got old retained checksum from broker. (The homie device
usually has not sent the new $fw/checksum at this moment).
Now the script uses the firmware MD5 only if it has been sent from a
"ready" device (or $online != false device to support v2.x devices).

Fix #589: ota-updater.py for V2 and V3 devices

---

docs/others/cpp-api-reference.md
src/Homie.cpp
src/Homie.hpp

doDeepSleep: changed the datatype of time_us to uint64_t, according to ESP8266 Arduino core 2.4.1
As a result it is possible to set durations longer than ~71min.

Closes: #652; doDeepSleep: changed the datatype of time_us to uint64_t

---

src/Homie/Config.cpp
src/Homie/Config.hpp

* More flexible patching
* Better readable code

Use recursive config patching

---

src/Homie.cpp

Implicitly enable LED feedback when a LED pin is set to allow using the LED pin on the ESP32 platform.
Fixes #663

Enable LED feedback when LED pin is set

---

src/Homie/Boot/BootNormal.cpp

There's a missing #if clause, which prevent the homie build for an ESP environment with "-D HOMIE_MDNS=0".
This PR add the missing #if, so that a build with disabled mDNS is possible.
The #if clause is missing in these branches:
- develop
- master
- v3.0
The PR is only for the develop-branch, but cherry-picking for the other branches should be possible.
Regards,
Thomas

Fix missing "#if HOMIE_MDNS" clause inside BootNormal::_onWifiGotIp
